# Generated by Django 2.2.4 on 2022-07-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycafe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitems',
            old_name='mane',
            new_name='name',
        ),
    ]
